#!/bin/bash

autologin=true
chaotic_aur=true
# Installing Chaotic AUR
if [ $chaotic_aur ]
then
curl -q https://codeberg.org/RaptaG/CAAIS/raw/branch/main/CAAIS > CAAIS
chmod +x CAAIS
sudo ./CAAIS -i
fi
# Instaling packagess
sudo pacman --needed --noconfirm -S - < PACKAGES.txt
paru --needed --noconfirm -S - < AUR.txt 

#  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
sudo systemctl enable NetworkManager
sudo systemctl enable bluetooth.service

sudo usermod -aG video $USER
brillo -c -S 1
chsh -s /usr/bin/zsh

##autologin
if [ $autologin ]
then
sudo mkdir /etc/systemd/system/getty@tty1.service.d/
sudo touch /etc/systemd/system/getty@tty1.service.d/autologin.conf
echo "[Service]" | sudo tee -a /etc/systemd/system/getty@tty1.service.d/autologin.conf
echo "ExecStart="  | sudo tee -a /etc/systemd/system/getty@tty1.service.d/autologin.conf
echo "ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin $USER - \$TERM" | sudo tee -a /etc/systemd/system/getty@tty1.service.d/autologin.conf
fi

##.dots
mkdir $HOME/{Downloads,Music,Documents}
mv .* $HOME
mv Pictures $HOME

# setup for symlinks
ln -fs $HOME/.cache/wal/dunstrc $HOME/.config/dunst/dunstrc
ln -fs $HOME/.cache/wal/starship $HOME/.config/starship.toml
ln -fs $HOME/.cache/wal/config_waybar $HOME/.config/waybar/config
ln -fs $HOME/.cache/wal/zathurarc $HOME/.config/zathura/zathurarc
ln -fs $HOME/.cache/wal/colors.css $HOME/.config/firefox/chrome/styles/colors.css
